### ISSUE TITLE
Primeira versão de dashboard

### ISSUE THREAD

**Issue by LucaSarhan** [Inteli-College/2024-T0002-EC09-G01#32]
Primeira versão em streamlit mostrando os dados do banco de dados com testes comprovando seu funcionamento.
1. Dash em streamlit
2. Conexão com o banco de dados
3. Criar os testes

**Comment by emanuelemorais** [comment]
5 - Primeira versão de dashboard (e.g., Streamlit) mostrando os dados do banco de dados estruturado, com testes comprovando seu funcionamento (até 2,0 pontos)
