### ISSUE TITLE
Análise de riscos e um plano de gestão de riscos do projeto

### ISSUE THREAD

**Issue by FelipeCampos14** [Inteli-College/2024-T0002-EC09-G01#6]

**Comment by LucaSarhan** [comment]
Link da docs com o plane da gestão de risco: https://docs.google.com/document/d/178SwTzCTdKqGn4kWLLI2q0UIYjMxzJs_ufaCwt1_2cw/edit?usp=sharing
Link do miro com os riscos:
https://miro.com/app/board/uXjVNvfMUFI=/
